name: Build and deploy Python app to Azure Web App - church-group-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Change to app directory
        run: cd app
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: app/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6DF3870FC8364F648BA50BBC4153B1C0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E8C4DC882444AD8AF85623DC28F4FBC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB1BCAF7F4184F38AC01B6EEF4FAEC37 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: church-group-bot-djg3hufte8bsh5cw
          slot-name: Production
          package: app/